name: CI_pull
on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get your cache directory path
        id: steps.yarn-cache-dir-path.outputs.dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn run format:check
      - run: yarn test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain tight-riddle.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
